# Render.com deployment configuration
python_version = "3.11.0"

[build]
# Build command - install dependencies
build = "pip install -r requirements.txt"

[web]
# Start command for the web service
start = "gunicorn --bind 0.0.0.0:$PORT run:app"

[env]
# Environment variables
PYTHON_VERSION = "3.11.0"
